name: 创建每日记录文件

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点执行
  workflow_dispatch:

jobs:
  create-log:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 创建当日记录文件
        run: |
          python scripts/new_log.py
      
      - name: 提交新记录
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add logs/
          git commit -m "自动创建今日精听记录模板" || echo "没有变更需要提交"
          git push 