name: 部署GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 配置GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: 上传页面制品
        uses: actions/upload-pages-artifact@v2
        with:
          path: './website'
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 