name: 部署GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Pages
        uses: actions/configure-pages@v3
        
      - name: 复制网站文件到根目录
        run: |
          cp -r website/* .
          ls -la
        
      - name: 上传页面制品
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 