name: 简化GitHub Pages部署

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        
      - name: 设置Pages
        uses: actions/configure-pages@v2
        
      - name: 设置工作目录
        run: |
          mkdir -p _site
          cp -r . _site/
          cd _site
          
          # 创建简单页面
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>精听记录</title>
          </head>
          <body>
            <h1>精听练习记录</h1>
            <p><a href="website/index.html">点击这里</a>进入精听记录系统</p>
          </body>
          </html>
          EOF
          
      - name: 上传页面制品
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 